-- The database schema

CREATE TABLE Managers (
	Manager_id number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Name varchar2(255) NOT NULL,
	email varchar2(255) NOT NULL
);

CREATE TABLE Projects (
	ProjectID number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ProjectDetail varchar2(255) NOT NULL,
	StartDate date NOT NULL,
	estEndDate date NOT NULL,
	Manager_id number(10) NOT NULL,
    CONSTRAINT proj_man FOREIGN KEY (Manager_id) REFERENCES Managers(Manager_id)
);

CREATE TABLE Employees (
	emp_id number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar2(255) NOT NULL,
	email varchar2(255) NOT NULL,
	Manager_ID number(10) NOT NULL,
	ProjectID number(10),
    CONSTRAINT emp_fk1 FOREIGN KEY (Manager_ID) REFERENCES Managers(Manager_ID),
    CONSTRAINT emp_fk2 FOREIGN KEY (ProjectID) REFERENCES Projects(ProjectID)
);

CREATE TABLE Species (
	SpeciesID number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SName varchar2(255) NOT NULL,
	SDes varchar2(255) NOT NULL
);

CREATE TABLE Reserves (
	ReserveID number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	RTitle varchar2(255) NOT NULL,
	SpeciesID number(10) NOT NULL,
    CONSTRAINT res_spe FOREIGN KEY (SpeciesID) REFERENCES Species(SpeciesID)
);

CREATE TABLE Tasks (
	task_id number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_desc varchar2(255) NOT NULL,
	assigned_time date NOT NULL,
	ReserveID number(10) NOT NULL,
    CONSTRAINT tsk_fk FOREIGN KEY (ReserveID) REFERENCES Reserves(ReserveID)
);

CREATE TABLE Assignments (
	emp_id number(10) NOT NULL,
	task_id number(10) NOT NULL,
	urgency number(1) NOT NULL,
	CONSTRAINT ass_comp_key PRIMARY KEY (emp_id, task_id),
    CONSTRAINT ass_fk FOREIGN KEY (task_id) REFERENCES Tasks(task_id),
    CONSTRAINT ass_fk2 FOREIGN KEY (emp_id) REFERENCES Employees(emp_id)
);


CREATE TABLE VisitorLogging (
	visitor_no number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	entry_time number(10) NOT NULL
);

CREATE TABLE Complaints (
	complaint_num number(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	complaint varchar2(255) NOT NULL,
	manager_id number(10),
	emp_id number(10) NOT NULL,
    CONSTRAINT com_emp FOREIGN KEY (emp_id) REFERENCES Employees(emp_id)
);

-- Adding data
-- Insert values into Manager table
INSERT INTO Managers (Name, email) VALUES ('Alice Johnson', 'alice.j@example.com');
INSERT INTO Managers (Name, email) VALUES ('Bob Smith', 'bob.s@example.com');

-- Insert values into Species table
INSERT INTO Species (SName, SDes) VALUES ('Elephant', 'Large mammal with a trunk');
INSERT INTO Species (SName, SDes) VALUES ('Tiger', 'Large cat with stripes');

-- Insert values into Reserves table
INSERT INTO Reserves (RTitle, SpeciesID) VALUES ('Elephant Reserve', 1);
INSERT INTO Reserves (RTitle, SpeciesID) VALUES ('Tiger Reserve', 2);

-- Insert values into Projects table
INSERT INTO Projects (ProjectDetail, StartDate, estEndDate, Manager_id) 
VALUES ('Wildlife Conservation', DATE '2024-01-01', DATE '2024-12-31', 1);
INSERT INTO Projects (ProjectDetail, StartDate, estEndDate, Manager_id) 
VALUES ('Tiger Habitat Restoration', DATE '2024-03-15', DATE '2025-03-15', 2);

-- Insert values into Employees table
INSERT INTO Employees (name, email, Manager_ID, ProjectID) 
VALUES ('John Doe', 'john.doe@example.com', 1, 1);
INSERT INTO Employees (name, email, Manager_ID, ProjectID) 
VALUES ('Jane Smith', 'jane.smith@example.com', 2, 2);

-- Insert values into Task table
INSERT INTO Tasks (task_desc, assigned_time, ReserveID) VALUES ('Feed the elephants', DATE '2024-08-10', 1);
INSERT INTO Tasks (task_desc, assigned_time, ReserveID) VALUES ('Monitor tiger health', DATE '2024-08-11', 2);

-- Insert values into Assignments table
INSERT INTO Assignments (emp_id, task_id, urgency) VALUES (1, 1, 2);
INSERT INTO Assignments (emp_id, task_id, urgency) VALUES (2, 2, 3);

-- Insert values into VisitorLogging table
INSERT INTO VisitorLogging (entry_time) VALUES (1630);
INSERT INTO VisitorLogging (entry_time) VALUES (1415);

-- Insert values into Complaints table
INSERT INTO Complaints (complaint, manager_id, emp_id) 
VALUES ('Overcrowded enclosure', 1, 1);
INSERT INTO Complaints (complaint, manager_id, emp_id) 
VALUES ('Noise from visitors', 2, 2);

/
--DROP TABLE VisitorLogging;
--DROP TABLE Projects;
--DROP TABLE Manager;
--DROP TABLE Employees;
--DROP TABLE Assignments;
--DROP TABLE Task;
--DROP TABLE Complaints;
--DROP TABLE Reserves;
--DROP TABLE Species;