-- The database schema

CREATE TABLE MANAGERS (
	MANAGER_ID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL
);

CREATE TABLE PROJECTS (
	PROJECTID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	PROJECTDETAIL VARCHAR2(255) NOT NULL,
	STARTDATE DATE NOT NULL,
	ESTENDDATE DATE NOT NULL,
	MANAGER_ID NUMBER(10) NOT NULL,
	CONSTRAINT PROJ_MAN FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS(MANAGER_ID)
);

CREATE TABLE EMPLOYEES (
	EMP_ID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	MANAGER_ID NUMBER(10) NOT NULL,
	PROJECTID NUMBER(10),
	CONSTRAINT EMP_FK1 FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS(MANAGER_ID),
	CONSTRAINT EMP_FK2 FOREIGN KEY (PROJECTID) REFERENCES PROJECTS(PROJECTID)
);

CREATE TABLE SPECIES (
	SPECIESID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SNAME VARCHAR2(255) NOT NULL,
	SDES VARCHAR2(255) NOT NULL
);

CREATE TABLE RESERVES (
	RESERVEID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	RTITLE VARCHAR2(255) NOT NULL,
	SPECIESID NUMBER(10) NOT NULL,
	CONSTRAINT RES_SPE FOREIGN KEY (SPECIESID) REFERENCES SPECIES(SPECIESID)
);

CREATE TABLE TASKS (
	TASK_ID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	TASK_DESC VARCHAR2(255) NOT NULL,
	ASSIGNED_TIME DATE NOT NULL,
	RESERVEID NUMBER(10) NOT NULL,
	COMPLETED NUMBER(1) DEFAULT 0,
	CONSTRAINT TSK_FK FOREIGN KEY (RESERVEID) REFERENCES RESERVES(RESERVEID)
);

CREATE TABLE ASSIGNMENTS (
	EMP_ID NUMBER(10) NOT NULL,
	TASK_ID NUMBER(10) NOT NULL,
	URGENCY NUMBER(1) NOT NULL,
	CONSTRAINT ASS_COMP_KEY PRIMARY KEY (EMP_ID, TASK_ID),
	CONSTRAINT ASS_FK FOREIGN KEY (TASK_ID) REFERENCES TASKS(TASK_ID),
	CONSTRAINT ASS_FK2 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE VISITORLOGGING (
	VISITOR_NO NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	ENTRY_TIME NUMBER(10) NOT NULL
);

CREATE TABLE COMPLAINTS (
	COMPLAINT_NUM NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	COMPLAINT VARCHAR2(255) NOT NULL,
	MANAGER_ID NUMBER(10),
	EMP_ID NUMBER(10) NOT NULL,
	CONSTRAINT COM_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE LOGINDATABASE (
	DATA_ID NUMBER(10) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	L_PASSWORD VARCHAR2(255) NOT NULL,
	STATUS CHAR(1) NOT NULL,
	CONSTRAINT LOG_IN PRIMARY KEY (EMAIL)
);


-- Adding data

-- Insert tasks for Elephant Reserve
INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID) 
VALUES ('Clean the elephant enclosure', DATE '2024-08-15', 1);

INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID) 
VALUES ('Prepare food for elephants', DATE '2024-08-16', 1);

-- Insert tasks for Tiger Reserve
INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID) 
VALUES ('Check tiger water supply', DATE '2024-08-20', 2);

INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID) 
VALUES ('Inspect tiger habitat fence', DATE '2024-08-25', 2);

-- Assignments for Employee 1 (John Doe) - Tasks related to Elephant Reserve
INSERT INTO ASSIGNMENTS (EMP_ID, TASK_ID, URGENCY) VALUES (1, 3, 2); -- Clean the elephant enclosure
INSERT INTO ASSIGNMENTS (EMP_ID, TASK_ID, URGENCY) VALUES (1, 4, 1); -- Prepare food for elephants

-- Assignments for Employee 2 (Jane Smith) - Tasks related to Tiger Reserve
INSERT INTO ASSIGNMENTS (EMP_ID, TASK_ID, URGENCY) VALUES (2, 5, 3); -- Check tiger water supply
INSERT INTO ASSIGNMENTS (EMP_ID, TASK_ID, URGENCY) VALUES (2, 6, 2); -- Inspect tiger habitat fence

-- -- Insert tasks for other potential reserves (example: Lion Reserve)
-- INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID) 
-- VALUES ('Monitor lion behavior', DATE '2024-09-01', 3);

-- INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID) 
-- VALUES ('Clean lion feeding area', DATE '2024-09-05', 3);

-- Insert values into Manager table
INSERT INTO MANAGERS (
	NAME,
	EMAIL
) VALUES (
	'Alice Johnson',
	'alice.j@example.com'
);

INSERT INTO MANAGERS (
	NAME,
	EMAIL
) VALUES (
	'Bob Smith',
	'bob.s@example.com'
);

-- Insert values into Species table
INSERT INTO SPECIES (
	SNAME,
	SDES
) VALUES (
	'Elephant',
	'Large mammal with a trunk'
);

INSERT INTO SPECIES (
	SNAME,
	SDES
) VALUES (
	'Tiger',
	'Large cat with stripes'
);

-- Insert values into Reserves table
INSERT INTO RESERVES (
	RTITLE,
	SPECIESID
) VALUES (
	'Elephant Reserve',
	1
);

INSERT INTO RESERVES (
	RTITLE,
	SPECIESID
) VALUES (
	'Tiger Reserve',
	2
);

-- Insert values into Projects table
INSERT INTO PROJECTS (
	PROJECTDETAIL,
	STARTDATE,
	ESTENDDATE,
	MANAGER_ID
) VALUES (
	'Wildlife Conservation',
	DATE '2024-01-01',
	DATE '2024-12-31',
	1
);

INSERT INTO PROJECTS (
	PROJECTDETAIL,
	STARTDATE,
	ESTENDDATE,
	MANAGER_ID
) VALUES (
	'Tiger Habitat Restoration',
	DATE '2024-03-15',
	DATE '2025-03-15',
	2
);

-- Insert values into Employees table
INSERT INTO EMPLOYEES (
	NAME,
	EMAIL,
	MANAGER_ID,
	PROJECTID
) VALUES (
	'John Doe',
	'john.doe@example.com',
	1,
	1
);

INSERT INTO EMPLOYEES (
	NAME,
	EMAIL,
	MANAGER_ID,
	PROJECTID
) VALUES (
	'Jane Smith',
	'jane.smith@example.com',
	2,
	2
);

-- Insert values into Task table
INSERT INTO TASKS (
	TASK_DESC,
	ASSIGNED_TIME,
	RESERVEID
) VALUES (
	'Feed the elephants',
	DATE '2024-08-10',
	1
);

INSERT INTO TASKS (
	TASK_DESC,
	ASSIGNED_TIME,
	RESERVEID
) VALUES (
	'Monitor tiger health',
	DATE '2024-08-11',
	2
);

-- Insert values into Assignments table
INSERT INTO ASSIGNMENTS (
	EMP_ID,
	TASK_ID,
	URGENCY
) VALUES (
	1,
	1,
	2
);

INSERT INTO ASSIGNMENTS (
	EMP_ID,
	TASK_ID,
	URGENCY
) VALUES (
	2,
	2,
	3
);

-- Insert values into VisitorLogging table
INSERT INTO VISITORLOGGING (
	ENTRY_TIME
) VALUES (
	1630
);

INSERT INTO VISITORLOGGING (
	ENTRY_TIME
) VALUES (
	1415
);

-- Insert values into Complaints table
INSERT INTO COMPLAINTS (
	COMPLAINT,
	MANAGER_ID,
	EMP_ID
) VALUES (
	'Overcrowded enclosure',
	1,
	1
);

INSERT INTO COMPLAINTS (
	COMPLAINT,
	MANAGER_ID,
	EMP_ID
) VALUES (
	'Noise from visitors',
	2,
	2
);

/
CREATE OR REPLACE PROCEDURE AddProject (
    ManagerID IN NUMBER,
    ProjectDet IN VARCHAR2,
    StartDate IN DATE,
    EndDate IN DATE
) IS
BEGIN
    INSERT INTO PROJECTS (
        PROJECTDETAIL, STARTDATE, ESTENDDATE, MANAGER_ID
    ) VALUES (
        ProjectDet, StartDate, EndDate, ManagerID
    );
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error adding project. Check inputs.');
END;
/

CREATE OR REPLACE TRIGGER CHECK_TASK_COMPLETION
AFTER UPDATE OR DELETE ON ASSIGNMENTS
FOR EACH ROW
DECLARE
    unresolved_count NUMBER;
BEGIN
    -- Count unresolved assignments for the affected task
    SELECT COUNT(*)
    INTO unresolved_count
    FROM ASSIGNMENTS
    WHERE TASK_ID = :OLD.TASK_ID;

    -- If there are no unresolved assignments, mark the task as completed
    IF unresolved_count = 0 THEN
        UPDATE TASKS
        SET COMPLETED = 1
        WHERE TASK_ID = :OLD.TASK_ID;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE AddTaskForAssignment (
    p_task_desc IN VARCHAR2,      -- Description of the task
    p_assigned_time IN DATE,      -- Assigned time for the task
    p_reserveid IN NUMBER,        -- Reserve ID
    p_emp_id IN NUMBER,           -- Employee ID to assign the task
    p_urgency IN NUMBER           -- Urgency level
) AS
    v_task_id NUMBER;             -- Variable to store the ID of the created task
BEGIN
    -- Insert a new task into the TASKS table
    INSERT INTO TASKS (TASK_DESC, ASSIGNED_TIME, RESERVEID)
    VALUES (p_task_desc, p_assigned_time, p_reserveid)
    RETURNING TASK_ID INTO v_task_id; -- Get the generated TASK_ID

    -- Insert the corresponding assignment into the ASSIGNMENTS table
    INSERT INTO ASSIGNMENTS (EMP_ID, TASK_ID, URGENCY)
    VALUES (p_emp_id, v_task_id, p_urgency);

    -- Optional: Log the operation (for debugging or audit purposes)
    DBMS_OUTPUT.PUT_LINE('Task created with ID: ' || v_task_id || ' and assigned to EMP_ID: ' || p_emp_id);
END;
/



CREATE OR REPLACE TRIGGER LOGINDATAE AFTER
	INSERT ON EMPLOYEES FOR EACH ROW
BEGIN
	IF INSERTING THEN
		INSERT INTO LOGINDATABASE (
			DATA_ID,
			EMAIL,
			L_PASSWORD,
			STATUS
		) VALUES (
			:NEW.EMP_ID,
			:NEW.EMAIL,
			:NEW.NAME,
			'E'
		);
	END IF;
END;
/

CREATE OR REPLACE TRIGGER LOGINDATAM AFTER
	INSERT OR DELETE ON MANAGERS FOR EACH ROW
BEGIN
	IF INSERTING THEN
		INSERT INTO LOGINDATABASE (
			DATA_ID,
			EMAIL,
			L_PASSWORD,
			STATUS
		) VALUES (
			:NEW.MANAGER_ID,
			:NEW.EMAIL,
			:NEW.NAME,
			'M'
		);
	END IF;
END;
/
/*
select * from LOGINDATABASE;
UPDATE LOGINDATABASE SET L_Password = 'A' WHERE email = 'alice.j@example.com';
UPDATE LOGINDATABASE SET L_Password = 'S' WHERE email = 'jane.smith@example.com';
select * from LOGINDATABASE;
/*
UPDATE LOGINDATABASE SET L_Password = 'Alice3' WHERE email = 'alice.j@example.com';

SELECT * FROM LoginDatabase WHERE email = 'alice.j@example.com';
select * from employees where MANAGER_ID = 1;
select * from PROJECTS;
select * from tasks;
select task_id, task_desc, assigned_time, reserveId, urgency from assignments
inner join employees using (emp_id) 
inner join tasks using (task_id)
WHERE MANAGER_ID = 1;
select * from projects;
*/
/*
TRUNCATE TABLE LoginDatabase;
DROP TABLE LoginDatabase;
TRUNCATE TABLE VisitorLogging;
DROP TABLE VisitorLogging;
TRUNCATE TABLE Assignments;
DROP TABLE Assignments;
TRUNCATE TABLE Tasks;
DROP TABLE Tasks;
TRUNCATE TABLE Reserves;
DROP TABLE Reserves;
TRUNCATE TABLE Species;
DROP TABLE Species;
TRUNCATE TABLE Complaints;
DROP TABLE Complaints;
TRUNCATE TABLE Employees;
DROP TABLE Employees;
TRUNCATE TABLE Projects;
DROP TABLE Projects;
TRUNCATE TABLE Managers;
DROP TABLE Managers;
*/